spring:
  application:
    name: community-service
  config:
    #    activate.on-profile: dev
    import:
      optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: Asia/Seoul
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        highlight_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm.jdbc.bind: trace
      springframework:
        orm.jpa: debug
        web: debug
        transaction: debug
#server:
#  port: ${PORT}
