name: Build test & Push

on:
  pull_request:
    branches: [ main, dev ]
  push:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'oracle'
      
      # Gradle
      - name: grant execute permission for gradlew
        run: chmod +x gradlew

      - name: build test with gradle
        run: ./gradlew build test --build-cache --parallel --stacktrace -info

      # build & push docker image
      - name: log in to docker hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build & push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          file: Dockerfile
          tags: ${{ secrets.DOCKER_TAG }}